<?php

return [
    'codes' => [
        10   => ['no' => 'Immaterielle eiendeler o.l', 'en' => 'Intangible fixed assets etc.', 'nature' => 'Real', 'subledger' => 'Main Balance sheet item', 'notes' => ''],
        1000 => ['no' => 'Forskning og utvikling', 'en' => 'Research and development', 'nature' => 'Real', 'subledger' => 'Intangible Asset', 'notes' => ''],
        1020 => ['no' => 'Konsesjoner', 'en' => 'Concessions', 'nature' => 'Real', 'subledger' => 'Intangible Asset', 'notes' => ''],
        1030 => ['no' => 'Patenter', 'en' => 'Patents', 'nature' => 'Real', 'subledger' => 'Intangible Asset', 'notes' => ''],
        1040 => ['no' => 'Lisenser', 'en' => 'Licenses', 'nature' => 'Real', 'subledger' => 'Intangible Asset', 'notes' => ''],
        1050 => ['no' => 'Varemerker', 'en' => 'Trademarks', 'nature' => 'Real', 'subledger' => 'Intangible Asset', 'notes' => ''],
        1060 => ['no' => 'Andre rettigheter', 'en' => 'Trademarks', 'nature' => 'Real', 'subledger' => 'Intangible Asset', 'notes' => ''],
        1070 => ['no' => 'Utsatt skattfordel', 'en' => 'Deferred tax assets', 'nature' => 'Real', 'subledger' => 'Deffered Long term Assets', 'notes' => ''],
        1080 => ['no' => 'Goodwill', 'en' => 'Goodwill', 'nature' => 'Real', 'subledger' => 'Goodwill', 'notes' => ''],
        11   => ['no' => 'Tomter, bygninger og annen fast eiendom', 'en' => 'Land, buildings and other real property', 'nature' => 'Real', 'subledger' => 'Main Balance sheet item', 'notes' => ''],
        1100 => ['no' => 'Bygninger', 'en' => 'Land, buildings and other real property', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        1120 => ['no' => 'Bygningsmessige anlegg', 'en' => 'Structural installations', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        1130 => ['no' => 'Anlegg under utførelse', 'en' => 'Plants under construction', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        1140 => ['no' => 'Jord- og skogbrukseiendommer', 'en' => 'Agricultural and forestry property', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        1150 => ['no' => 'Tomter og andre grunnarealer', 'en' => ' Land and other real property', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        1160 => ['no' => 'Boliger inklusive tomter', 'en' => 'Dwellings (incl. building sites)', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        1180 => ['no' => 'Investeringseiendommer', 'en' => 'Investment property', 'nature' => 'Real', 'subledger' => 'Land, buildings and other real property', 'notes' => ''],
        12   => ['no' => 'Transportmidler, inventar og maskiner o.l.', 'en' => 'Means of transport fixtures, fittings, machinery etc.', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => 'The Individual Assets should be accordingly grouped and plant & mach, etc should behave as sub ledgers'],
        1200 => ['no' => 'Maskiner og anlegg', 'en' => 'Plant and machinery', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1210 => ['no' => 'Maskiner og anlegg under utførelse', 'en' => 'Plant and machinery under construction', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1220 => ['no' => 'Skip, rigger, fly', 'en' => 'Ships, rigs, aircrafts', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1230 => ['no' => 'Biler', 'en' => 'Motor vehicles', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1240 => ['no' => 'Andre transportmidler', 'en' => 'Other means of transport', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1250 => ['no' => 'Inventar', 'en' => 'Fixtures and fittings', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1260 => ['no' => 'Bygninger med annen avskrivningstid', 'en' => 'Permanent building fixtures with a depreciation period different from the building.', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1270 => ['no' => 'Verktøy mv.', 'en' => 'Tools etc.', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        1280 => ['no' => 'Kontormaskiner', 'en' => 'Office machines', 'nature' => 'Real', 'subledger' => 'Property Plant & Equipment', 'notes' => ''],
        13   => ['no' => 'Finansielle anleggsmidler', 'en' => 'Financial fixed assets', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1300 => ['no' => 'Investeringer i datterselskaper', 'en' => 'Investments in subsidiaries', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ' the components of each these items should behave as subledgers. Eg inv in XYZ corporation, etc'],
        1310 => ['no' => 'Investeringer annet foretak i samme konsern', 'en' => 'Investments in other group companies', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ''],
        1320 => ['no' => 'Lån til foretak samme konsern', 'en' => 'Loan to group companies', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ''],
        1330 => ['no' => 'Investeringer i tilknyttede selskap', 'en' => 'Investments in associated companies', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ''],
        1340 => ['no' => 'Lån til tilknyttede selskap', 'en' => 'Loans to associated companies and joint ventures', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ''],
        1350 => ['no' => 'Investeringer i aksjer og eiendeler', 'en' => 'Investments in shares, units and securities fund units.', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ''],
        1360 => ['no' => 'Obligasjoner', 'en' => 'Investments in shares, units and securities fund units.', 'nature' => 'Real', 'subledger' => 'Long term Investments', 'notes' => ''],
        1370 => ['no' => 'Fordringer på eiere og styremedlemmer', 'en' => 'Receivables from owners, board members etc.', 'nature' => 'Real', 'subledger' => 'Main Balance sheet item - under current asset', 'notes' => ''],
        1380 => ['no' => 'Fordringer på ansatte', 'en' => 'Receivables from employees', 'nature' => 'Real', 'subledger' => 'Main Balance sheet item - under current asset', 'notes' => ''],
        1390 => ['no' => 'Andre fordringer', 'en' => 'Other receivables', 'nature' => 'Real', 'subledger' => 'Main Balance sheet item - under current asset', 'notes' => ''],
        14   => ['no' => ' Varelager og forskudd til leverandører ', 'en' => 'Inventory (stocks) and prepayments to suppliers', 'nature' => 'Real', 'subledger' => 'Inventory', 'notes' => 'Stock items should be created under this item. This should be a balance sheet main item and when raw material is used the same should be transferred here when used manually. The WIP if completed should be transaferred here manually as per stock. Main item - the goods individual item should behave as sub ledger'],
        1400 => ['no' => 'Råvarer og innkjøpte halvfabrikater', 'en' => 'Raw materials and semi-manufactures', 'nature' => 'Real', 'subledger' => 'Inventory', 'notes' => ''],
        1420 => ['no' => 'Varer under utvikling', 'en' => 'Work in progress', 'nature' => 'Real', 'subledger' => 'Inventory', 'notes' => ''],
        1440 => ['no' => 'Ferdige egentilvirkede varer', 'en' => 'Self-produced finished goods', 'nature' => 'Real', 'subledger' => 'Inventory', 'notes' => ''],
        1460 => ['no' => 'Innkjøpte varer for videresalg', 'en' => 'goods purchased for resale', 'nature' => 'Real', 'subledger' => 'Inventory', 'notes' => ''],
        1480 => ['no' => 'Forskuddsbetaling til leverandører', 'en' => 'Prepayments to suppliers (contracts for goods/projects)', 'nature' => 'Real', 'subledger' => 'Advances ', 'notes' => ''],
        1490 => ['no' => 'Biologiske eiendeler', 'en' => 'Biological assets', 'nature' => 'Real', 'subledger' => 'Advances ', 'notes' => ''],
        15   => ['no' => 'Kortsiktige fordringer ', 'en' => 'Short-term receivables', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        1500 => ['no' => 'Kundefordringer', 'en' => 'Accounts receivable from customers', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        1530 => ['no' => 'Opptjent ikke fakturert inntekt', 'en' => 'Accrued unvoiced operating revenue.', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        1550 => ['no' => 'Kundefordringer på selskap samme konsern', 'en' => 'Accounts receivable from companies in the same group', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        1560 => ['no' => 'Andre fordringer på selskap samme konsern', 'en' => 'Other receivables from companies in the same group', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        1570 => ['no' => 'Andre kortsiktige fordringer', 'en' => 'Other short-term receivables', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        1580 => ['no' => 'Avsetning tap på fordringer', 'en' => 'Provisions for bad debts', 'nature' => 'Real', 'subledger' => 'Net receivables', 'notes' => ''],
        16   => ['no' => ' Merverdiavgift, opptjente offentlige tilskudd o.l.', 'en' => '16 Value-added tax, earned public grants etc.', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1600 => ['no' => 'Utgående merverdiavgift', 'en' => '160 Output value added tax', 'nature' => 'Real', 'subledger' => 'Sub ledger of Output Value Added Tax', 'notes' => ''],
        1601 => ['no' => 'Utgående merverdiavgift høy sats', 'en' => '161 Output value added tax high rate', 'nature' => 'Real', 'subledger' => 'Sub ledger of Output Value Added Tax', 'notes' => ''],
        1602 => ['no' => 'Utgående merverdiavgift kjøp tjen. fra utlandet', 'en' => '162 Output, value added tax services purchased outside Norway', 'nature' => 'Real', 'subledger' => 'Sub ledger of Output Value Added Tax', 'notes' => ''],
        1603 => ['no' => 'Utgående merverdiavgift middels sats', 'en' => '163 Output value added tax medium rate', 'nature' => 'Real', 'subledger' => 'Sub ledger of Output Value Added Tax', 'notes' => ''],
        1604 => ['no' => 'Utgående merverdiavgift lav sats', 'en' => '164 Output value added tax low rate', 'nature' => 'Real', 'subledger' => 'Sub ledger of Output Value Added Tax', 'notes' => ''],
        1610 => ['no' => 'Inngående merverdiavgift', 'en' => '160 Input value added tax', 'nature' => 'Real', 'subledger' => 'Sub ledger of Input Value Added Tax', 'notes' => ''],
        1611 => ['no' => 'Inngående merverdiavgift høy sats', 'en' => '161 Input value added tax high rate', 'nature' => 'Real', 'subledger' => 'Sub ledger of Input Value Added Tax', 'notes' => ''],
        1612 => ['no' => 'Inngående merverdiavgift kjøp tjen. fra utlandet', 'en' => '162 Input, value added tax services purchased outside Norway', 'nature' => 'Real', 'subledger' => 'Sub ledger of Input Value Added Tax', 'notes' => ''],
        1613 => ['no' => 'Inngående merverdiavgift middels sats', 'en' => '163 Input value added tax medium rate', 'nature' => 'Real', 'subledger' => 'Sub ledger of Input Value Added Tax', 'notes' => ''],
        1614 => ['no' => 'Inngående merverdiavgift lav sats', 'en' => '164 Input value added tax low rate', 'nature' => 'Real', 'subledger' => 'Sub ledger of Input Value Added Tax', 'notes' => ''],
        1620 => ['no' => 'Investeringsavgift', 'en' => 'N/A', 'nature' => '', 'subledger' => '', 'notes' => ''],
        1630 => ['no' => 'Grunnlag investeringsavgift', 'en' => 'N/A', 'nature' => '', 'subledger' => '', 'notes' => ''],
        1640 => ['no' => 'Oppgjørskonto merverdiavgift', 'en' => '164 Settlement account for value added tax', 'nature' => 'Real', 'subledger' => 'Current liabilities', 'notes' => ''],
        1670 => ['no' => 'Krav på offentlige tilskudd', 'en' => '167 Entitlements to public grants', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        17   => ['no' => ' Forskuddsbetalt kostnad, påløpt inntekt o.l. ', 'en' => '17 Prepaid expenses and accrued income, etc.', 'nature' => 'Real', 'subledger' => 'Other Current Asset', 'notes' => ''],
        1700 => ['no' => 'Forskuddsbetalte leier', 'en' => '170 Prepaid rental expenses', 'nature' => 'Real', 'subledger' => 'Other Current Asset', 'notes' => ''],
        1710 => ['no' => 'Forskuddsbetalte renter', 'en' => '171 Prepaid interest expenses', 'nature' => 'Real', 'subledger' => 'Other Current Asset', 'notes' => ''],
        1750 => ['no' => 'Påløpte leier', 'en' => '175 Accrued rental income', 'nature' => 'Real', 'subledger' => 'Other Current Asset', 'notes' => ''],
        1760 => ['no' => 'Påløpte renter', 'en' => '176 Accrued interest income', 'nature' => 'Real', 'subledger' => 'Other Current Asset', 'notes' => ''],
        1780 => ['no' => 'Krav på innbetaling av selskapskapital', 'en' => '178 Unpaid subscribed capital', 'nature' => 'Real', 'subledger' => 'Other Current Asset', 'notes' => ''],
        1790 => ['no' => 'Interimskonto', 'en' => 'N/A', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        18   => ['no' => ' Kortsiktige finansinvesteringer', 'en' => '18 Short-term financial investments', 'nature' => 'Real', 'subledger' => 'All these ledger can be grouped under Short term investment ( in main Balance sheet).  The individual investment should behave as sub ledger of these sub ledgers.  For eg. Investment in shares of xyz co. will be sub ledger of other share investments which will ultimately be grouped under Short term investment', 'notes' => ''],
        1800 => ['no' => 'Aksjer og andeler i foretak samme konsern', 'en' => '180 Shares and units in group companies', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1810 => ['no' => 'Markedsbaserte aksjer', 'en' => '181 Quoted investment shares and securities fund units.', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1820 => ['no' => 'Andre aksjer', 'en' => '182 Other share investments', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1830 => ['no' => 'Markedsbaserte obligasjoner', 'en' => '183 Market based bonds', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1840 => ['no' => 'Andre obligasjoner', 'en' => '184 Other bond investments', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1850 => ['no' => 'Markedsbaserte obligasjoner', 'en' => '185 Quoted bonds with a short maturity (certificates)', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1860 => ['no' => 'Andre sertifikater', 'en' => '186 Other bonds with a short maturity.', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1870 => ['no' => 'Andre markedsbaserte finansielle instrumenter', 'en' => '187 Other quoted financial instruments.', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        1880 => ['no' => 'Andre finansielle instrumenter', 'en' => '188 Other financial instruments.', 'nature' => 'Real', 'subledger' => '', 'notes' => ''],
        19   => ['no' => ' Bankinnskudd, kontanter og lignende ', 'en' => '19 Bank deposits, cash in hand etc.', 'nature' => 'Real', 'subledger' => 'Cash and Cash equivalent', 'notes' => ''],
        1900 => ['no' => 'Kontanter', 'en' => '190 Cash in hand', 'nature' => 'Real', 'subledger' => 'Cash and Cash equivalent', 'notes' => ''],
        1910 => ['no' => 'Kasse', 'en' => '191 cash-Registry', 'nature' => 'Real', 'subledger' => 'Cash and Cash equivalent', 'notes' => ''],
        1920 => ['no' => 'Bankinnskudd', 'en' => '192 Bank deposits', 'nature' => 'Real', 'subledger' => 'Cash and Cash equivalent', 'notes' => ''],
        1950 => ['no' => 'Bankinnskudd for skattetrekk', 'en' => '195 Bank deposits for tax withholdings.', 'nature' => 'Real', 'subledger' => 'Cash and Cash equivalent', 'notes' => ''],
        2    => ['no' => 'EGENKAPITAL OG GJELD ', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        20   => ['no' => 'Egenkapital AS/ASA', 'en' => '20 Equity, limited liability companies', 'nature' => 'Resulting effect', 'subledger' => '', 'notes' => ''],
        2000 => ['no' => 'Aksjekapital', 'en' => '200 Subscribed share capital', 'nature' => 'Real', 'subledger' => 'Stock holders Equity', 'notes' => ''],
        2010 => ['no' => 'Egne aksjer', 'en' => '201 Own shares (treasury stock)', 'nature' => 'Real', 'subledger' => 'Stock holders Equity', 'notes' => ''],
        2020 => ['no' => 'Overkursfond', 'en' => '202 Share premium reserve', 'nature' => 'Real', 'subledger' => 'Stock holders Equity', 'notes' => ''],
        2040 => ['no' => 'Fond for vurderingsforskjeller', 'en' => 'N/A', 'nature' => '', 'subledger' => 'Stock holders Equity', 'notes' => ''],
        2050 => ['no' => 'Annen egenkapital', 'en' => '203 Other paid-in capital', 'nature' => 'Real', 'subledger' => 'Stock holders Equity', 'notes' => ''],
        2080 => ['no' => 'Udekket tap', 'en' => 'Uncovered losses', 'nature' => 'Real', 'subledger' => 'Stock holders Equity', 'notes' => ''],
        21   => ['no' => 'Avsetning for forpliktelser ', 'en' => '21 provisions for liabilities and charges', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2100 => ['no' => 'Pensjonsforpliktelser', 'en' => '210 Pension liabilities', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2120 => ['no' => 'Utsatt skatt', 'en' => '212 Deferred tax', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2160 => ['no' => 'Uopptjent inntekt', 'en' => '216 Unearned income', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2180 => ['no' => 'Andre avsetninger for forpliktelser', 'en' => '218 Other provisions for liabilities and charges', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        22   => ['no' => 'Annen langsiktig gjeld ', 'en' => '22 Other long term liabilities', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2200 => ['no' => 'Konvertible lån', 'en' => '220 convertible loans', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2210 => ['no' => 'Obligasjonslån', 'en' => '221 Bond loans', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2220 => ['no' => 'Gjeld til kredittinstitusjoner', 'en' => '222 Liabilities to financial institutions', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2240 => ['no' => 'Pantelån', 'en' => 'N/A', 'nature' => '', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2260 => ['no' => 'Gjeld til selskap i samme konsern', 'en' => '225 Liabilities to employees and owners', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2270 => ['no' => 'Andre valutalån', 'en' => '227 Other currency loans', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        2280 => ['no' => 'Stille interessentinnskudd og ansv. lånekapital', 'en' => '228 Subscription by sleeping partner and subordinated loan capital', 'nature' => 'Real', 'subledger' => 'Long term liabilities', 'notes' => ''],
        23   => ['no' => 'Kortsiktige konvertible lån, obligasjonslån og gjeld til kredittinstitusjoner ', 'en' => '23 Short-term convertible loans, bond loans and liabilities to financial institutions.', 'nature' => 'Real', 'subledger' => 'Short term debt', 'notes' => ''],
        2300 => ['no' => 'Konvertible lån', 'en' => '230 Convertible loans', 'nature' => 'Real', 'subledger' => 'Short term debt', 'notes' => ''],
        2320 => ['no' => 'Setifikatlån', 'en' => '232 Bond loans', 'nature' => 'Real', 'subledger' => 'Short term debt', 'notes' => ''],
        2340 => ['no' => 'Andre valutalån', 'en' => 'Other currency loans', 'nature' => 'Real', 'subledger' => 'Short term debt', 'notes' => ''],
        2360 => ['no' => 'Byggelån', 'en' => '236 Construction loans', 'nature' => 'Real', 'subledger' => 'Short term debt', 'notes' => ''],
        2380 => ['no' => 'Kassekreditt', 'en' => '236 Construction loans', 'nature' => 'Real', 'subledger' => 'Short term debt', 'notes' => ''],
        24   => ['no' => 'Leverandørgjeld ', 'en' => '24 Trade creditors', 'nature' => 'Personal', 'subledger' => 'Accounts payable', 'notes' => ''],
        2400 => ['no' => 'Leverandørgjeld', 'en' => '240 Trade creditors', 'nature' => 'Personal', 'subledger' => 'Accounts payable', 'notes' => ''],
        2460 => ['no' => 'Leverandørgjeld til selskap i samme konsern', 'en' => '246 Trade creditors from group companies', 'nature' => 'Personal', 'subledger' => 'Accounts payable', 'notes' => ''],
        25   => ['no' => 'Betalbar skatt ', 'en' => '25 Tax payable', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => 'Should be further divided as group of duties and taxes'],
        2500 => ['no' => 'Betalbar skatt, ikke utlignet', 'en' => '250 tax payable, not offset', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2510 => ['no' => 'Betalbar skatt, utlignet', 'en' => '251 Tax payable, offset', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2530 => ['no' => 'Refusjon skatt etter Skatteloven §31 5. ledd', 'en' => 'N/A', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2540 => ['no' => 'Forhåndsskatt', 'en' => '254 Corporate advance tax', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        26   => ['no' => 'Skattetrekk og andre trekk ', 'en' => '26 Tax withholdings and other deductions', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => 'Should be further divided as group of duties and taxes'],
        2600 => ['no' => 'Forskuddstrekk', 'en' => '260 Advance tax withholding', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2610 => ['no' => 'Påleggstrekk', 'en' => '261 Attachment of earnings', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2620 => ['no' => 'Bidragstrekk', 'en' => '262 Deduction of support (child support etc.) payments', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2630 => ['no' => 'Trygdetrekk', 'en' => '263 National insurance deduction', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2640 => ['no' => 'Forsikringstrekk', 'en' => '264 Insurance deduction', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2650 => ['no' => 'Trukket fagforeningskontigent', 'en' => '265 trade union dues deduction', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        27   => ['no' => 'Skyldige offentlige avgifter ', 'en' => '27 Public duties payable', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => 'Should be further divided as group of duties and taxes'],
        2700 => ['no' => 'Utgående merverdiavgift', 'en' => '271 Output value added tax', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2701 => ['no' => 'Utgående merverdiavgift høy sats', 'en' => '271 Output value added tax high rate', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2702 => ['no' => 'Utgående merverdiavgift kjøp tjen. fra utlandet', 'en' => '272 Output, value added tax services purchased outside Norway', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2703 => ['no' => 'Utgående merverdiavgift middels sats', 'en' => '273 Output value added tax medium rate', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2704 => ['no' => 'Utgående merverdiavgift lav sats', 'en' => '274 Output value added tax low rate', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2710 => ['no' => 'Inngående merverdiavgift', 'en' => '271 Input value added tax', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2711 => ['no' => 'Inngående merverdiavgift høy sats', 'en' => '271 Input value added tax high rate', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2712 => ['no' => 'Inngående merverdiavgift kjøp tjen. fra utlandet', 'en' => '272 Input, value added tax services purchased outside Norway', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2713 => ['no' => 'Inngående merverdiavgift middels sats', 'en' => '273 Input value added tax medium rate', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2714 => ['no' => 'Inngående merverdiavgift lav sats', 'en' => '274 Input value added tax low rate', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2720 => ['no' => 'Investeringsavgift', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        2730 => ['no' => 'Grunnlag investeringsavgift', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        2740 => ['no' => 'Oppgjørskonto merverdiavgift', 'en' => '274 Settlement account for value added tax', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2770 => ['no' => 'Skyldig arbeidsgiveravgift', 'en' => '277 Unpaid employers’ national contributions', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2780 => ['no' => 'Påløpt arbeidsgiveravgift', 'en' => '278 Accrued employers’ national contributions', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        28   => ['no' => 'Utbytte ', 'en' => '28 Dividends', 'nature' => 'Nominal', 'subledger' => 'Appropriation', 'notes' => ''],
        2800 => ['no' => 'Avsatt utbytte', 'en' => '280 Provision for dividends', 'nature' => 'Real', 'subledger' => 'Appropriation', 'notes' => ''],
        29   => ['no' => ' Annen kortsiktig gjeld ', 'en' => '29 Other current liabilities', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2900 => ['no' => 'Forskudd fra kunder', 'en' => '290 Prepayments from customers', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2910 => ['no' => 'Gjeld til ansatte og eiere', 'en' => '291 Liabilities to employees and owners', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2920 => ['no' => 'Gjeld til selskap i samme konsern', 'en' => '292 Liabilities to companies in the same group', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2930 => ['no' => 'Lønn', 'en' => '293 Wages and salaries', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2940 => ['no' => 'Feriepenger', 'en' => '294 Holiday pay', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2950 => ['no' => 'Påløpte renter', 'en' => '295 Accrued expenses and prepaid income', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2960 => ['no' => 'Påløpt kostnad og forskuddsbetalt inntekt', 'en' => '297 Unearned income', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2970 => ['no' => 'Uopptjent inntekt', 'en' => '298 Provisions for liabilities', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        2980 => ['no' => 'Avsetninger og forpliktelser', 'en' => '299 Other current liabilities', 'nature' => 'Real', 'subledger' => 'Other current liabilities', 'notes' => ''],
        3    => ['no' => ' SALGS- OG DRIFTSINNTEKT ', 'en' => 'Class 3: Sales and operating income', 'nature' => '', 'subledger' => '', 'notes' => ''],
        30   => ['no' => 'Salgsinntekt, avgiftspliktig ', 'en' => '30 Sales revenue subject to value-added tax', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3000 => ['no' => 'Salgsinntekt handelsvarer avgiftspl. høy sats', 'en' => '300 Sales revenue, subject to value-added tax', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3010 => ['no' => 'Salgsinntekt egentilv. varer avgiftspl. høy sats', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3020 => ['no' => 'Salgsinntekt tjenester avgiftspl. høy sats', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3030 => ['no' => 'Salgsinntekt handelsvarer avgiftpl. middels sats', 'en' => 'Na', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3040 => ['no' => 'Salgsinntekt egentilv. varer avgiftpl middels sats', 'en' => 'Na', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3050 => ['no' => 'Salgsinntekter tjenester avgiftspl. lav sats', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3060 => ['no' => 'Uttak av varer avgiftspliktig høy sats', 'en' => '306 Withdrawal of goods', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3063 => ['no' => 'Uttak av varer avgiftspliktig middels sats', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3070 => ['no' => 'Uttak av tjenester avgiftspliktig høy sats', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3074 => ['no' => 'Uttak av tjenester avgiftspliktig lav sats', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3080 => ['no' => 'Rabatter og annen salgsinntektsred., avgiftspl.', 'en' => '308 Discounts and other sales revenue reductions', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3090 => ['no' => 'Refunderbare utlegg for kjøpers regning, avgiftspl', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        31   => ['no' => ' Salgsinntekt, avgiftsfri', 'en' => '31 Sales revenue, not subject to value-added tax', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3100 => ['no' => 'Salgsinntekt handelsvarer avgiftsfri', 'en' => '310 Sales revenue not subject to value-added tax', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3110 => ['no' => 'Salgsinntekt egentilvirkede varer avgiftsfri', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3120 => ['no' => 'Salgsinntekt tjenester avgiftsfri', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3160 => ['no' => 'Uttak av varer avgiftsfritt', 'en' => '310 Sales revenue not subject to value-added tax', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3180 => ['no' => 'Rabatter og annen salgsinntektreduksjon avgiftsfri', 'en' => '318 Discounts and other sales revenue reductions', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3190 => ['no' => 'Refunderbare utlegg for kjøpers regning, avg.fri', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        32   => ['no' => 'Salgsinntekt, utenfor avgiftsområdet ', 'en' => '32 Sales revenue outside the value-added tax area', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3200 => ['no' => 'Salgsinntekt handelsvarervarer utenfor avg.omr', 'en' => '320 Sales revenue outside the value-added tax area', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3210 => ['no' => 'Salgsinntekt egentilvirkede varer utenfor avg.omr', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3220 => ['no' => 'Salgsinntekt tjenester utenfor avg.omr', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3260 => ['no' => 'Uttak av varer utenfor avgiftsområdet', 'en' => '326 Withdrawal of goods', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        3280 => ['no' => 'Rabatter og annen salgsinntektsreduksjon', 'en' => '328 Discounts and other sales revenue Reductions', 'nature' => 'Nominal', 'subledger' => 'Sales', 'notes' => ''],
        33   => ['no' => 'Offentlig avgift vedr. omsetning ', 'en' => '33 Government fees and taxes related to sales', 'nature' => 'Nominal', 'subledger' => 'sub ledger of relevant duties and taxes', 'notes' => ''],
        3300 => ['no' => 'Spesiell off. avg. tilv./solgte varer avgiftspl.', 'en' => '330 Special government fees and taxes on goods produced/sold', 'nature' => 'Nominal', 'subledger' => 'sub ledger of relevant duties and taxes', 'notes' => ''],
        3301 => ['no' => 'Spesiell off. avg. tilv./solgte varer fritt', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3302 => ['no' => 'Miljø avgift for tilv./solgte varer avgiftspliktig', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        3303 => ['no' => 'Miljø avgift for tilv./solgte varer avgiftsfritt', 'en' => 'NA', 'nature' => '', 'subledger' => '', 'notes' => ''],
        34   => ['no' => 'Offentlig tilskudd/refusjon ', 'en' => '34 Public grants/refunds', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        3400 => ['no' => 'Spesielt offentlig tilskudd for tilv./solgte varer', 'en' => '340 Special public grant for manufactured/sold goods', 'nature' => 'Nominal', 'subledger' => 'Netted to cost of goods ', 'notes' => ''],
        3440 => ['no' => 'Spesielt offentlig tilskudd for tjeneste', 'en' => '340 Special public grant for manufactured/sold goods', 'nature' => 'Nominal', 'subledger' => 'Netted to cost of goods ', 'notes' => ''],
        35   => ['no' => 'Uopptjent inntekt ', 'en' => '35 Unearned income', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        3500 => ['no' => 'Garanti', 'en' => '350 Guarantees', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        3510 => ['no' => 'Service', 'en' => '351 Service', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        36   => ['no' => 'Leieinntekt ', 'en' => '36 Rental income', 'nature' => 'Nominal', 'subledger' => 'Rental Income', 'notes' => 'Should be grouped under Other Non operating Income'],
        3600 => ['no' => 'Leieinntekt fast eiendom', 'en' => '360 Rental income from real property', 'nature' => 'Nominal', 'subledger' => 'Rental Income', 'notes' => ''],
        3610 => ['no' => 'Leieinntekt andre varige driftsmidler', 'en' => '361 Rental income from other tangible fixed assets', 'nature' => 'Nominal', 'subledger' => 'Rental Income', 'notes' => ''],
        3620 => ['no' => 'Annen leieinntekt', 'en' => '362 Other rental income', 'nature' => 'Nominal', 'subledger' => 'Rental Income', 'notes' => ''],
        37   => ['no' => 'Provisjonsinntekt ', 'en' => '37 Commission income', 'nature' => 'Nominal', 'subledger' => 'Commission income', 'notes' => ''],
        3700 => ['no' => 'Provisjonsinntekt', 'en' => '370 Commission income', 'nature' => 'Nominal', 'subledger' => 'Commission income', 'notes' => ''],
        38   => ['no' => 'Gevinst ved avgang av anleggsmidler ', 'en' => '38 Profit on the sale of fixed assets (accounts 380-384) Change in value (accounts 385-389)', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3800 => ['no' => 'Gevinst ved avgang av anleggsmidler', 'en' => '380 Profit on the sale of fixed assets', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        39   => ['no' => 'Annen driftsrelatert inntekt ', 'en' => '39 Other operational income', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3900 => ['no' => 'Annen driftsrelatert inntekt, avgiftspliktig', 'en' => '390 Other operational income', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3910 => ['no' => 'Utgående porto, avgiftspliktig', 'en' => 'Outgoing stamp duty, taxable', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3920 => ['no' => 'Utgående gebyrer, avgiftspliktig', 'en' => 'Outgoing fees, taxable', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3950 => ['no' => 'Annen driftsrelatert inntekt, avgiftsfritt', 'en' => 'Other operational income, non-taxable', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3960 => ['no' => 'Utgående porto, avgiftsfritt', 'en' => 'Outgoing stamps - non-taxable', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        3970 => ['no' => 'Utgående gebyrer, avgiftsfritt', 'en' => 'Outgoing fees, - non-taxable', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income - misc', 'notes' => ''],
        4    => ['no' => 'VAREKOSTNAD ', 'en' => 'Class 4: cost of stocks', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        40   => ['no' => 'Forbruk av råvarer og innkjøpte halvfabrikater ', 'en' => '40 Consumption of raw materials and semi-manufactures', 'nature' => 'Nominal', 'subledger' => 'Refer another sheet of accounting entries', 'notes' => ''],
        4000 => ['no' => 'Innkjøp av råvarer og halvfabrikata høy sats', 'en' => '400 Purchase of raw materials and semi-manufactures full VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4030 => ['no' => 'Innkjøp av råvarer og halvfabrikata middels sats', 'en' => '403 Purchase of raw materials and semi-manufactures medium VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4060 => ['no' => 'Frakt, toll og spedisjon', 'en' => '406 Customs duty, freight and forwarding', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4070 => ['no' => 'Innkjøpsprisreduksjon', 'en' => '407 Purchase price reduction', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4090 => ['no' => 'Beholdningsendring', 'en' => '409 Change in stock', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        41   => ['no' => ' Forbruk av varer under tilvirkning', 'en' => '41 Consumption of work in progress', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4100 => ['no' => 'Innkjøp varer under tilvirkning høy sats', 'en' => '410 Purchase of work in progress FULL VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4130 => ['no' => 'Innkjøp varer under tilvirkning middels sats', 'en' => '410 Purchase of work in progress medium VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4160 => ['no' => 'Frakt, toll og spedisjon', 'en' => '416 Customs duty, freight and forwarding', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4170 => ['no' => 'Innkjøpsprisreduksjon', 'en' => '417 Purchase price reduction', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4190 => ['no' => 'Beholdningsendring', 'en' => '419 Change in stock', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        42   => ['no' => 'Forbruk av ferdig tilvirkede varer ', 'en' => '42 Consumption of finished goods', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4200 => ['no' => 'Innkjøp ferdig egentilvirkede varer høy sats', 'en' => '420 Purchase or self-produced finished goods MEDIUM VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4230 => ['no' => 'Innkjøp ferdig egentilvirkede varer middels sats', 'en' => '420 Purchase or self-produced finished goods MEDIUM VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4260 => ['no' => 'Frakt, toll og spedisjon', 'en' => '426 Customs duty, freight and forwarding', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4270 => ['no' => 'Innkjøpsprisreduksjon, avgiftspliktig', 'en' => '427 Purchase price reduction', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4290 => ['no' => 'Beholdningsendring', 'en' => '429 Change in stock.', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        43   => ['no' => 'Forbruk av innkjøpte varer for videresalg ', 'en' => '43 Consumption of goods purchased for resale:', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4300 => ['no' => 'Innkjøp varer for videresalg høy sats', 'en' => '430 Purchase of goods for resale full vat', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4330 => ['no' => 'Innkjøp varer for videresalg middels sats', 'en' => '430 Purchase of goods for resale medium VAT', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4360 => ['no' => 'Frakt, toll og spedisjon', 'en' => '436 Customs duty, freight and forwarding', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4370 => ['no' => 'Innkjøpsprisreduksjon', 'en' => '437 Purchase price reduction', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4390 => ['no' => 'Beholdningsendring', 'en' => '439 Change in stock', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        45   => ['no' => 'Fremmedytelse og underentreprise ', 'en' => '45 External services and subcontracts', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4500 => ['no' => 'Fremmedytelser og underentreprise', 'en' => '450 External services and subcontracts', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4590 => ['no' => 'Beholdningsendring', 'en' => '459 Change in stock', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        49   => ['no' => ' Annen periodisering ', 'en' => '49 Other accruals', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4900 => ['no' => 'Annen periodisering', 'en' => '490 Other accruals', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        4990 => ['no' => 'Beholdningsendring', 'en' => '499 Change in stock', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        5    => ['no' => 'LØNNSKOSTNAD ', 'en' => 'Class 5: Payroll costs', 'nature' => '', 'subledger' => '', 'notes' => ''],
        50   => ['no' => ' Lønn til ansatte', 'en' => '50 wages and salaries to employees', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => 'The individual items can be created as sub ledger depending upon the business of the user and volume of transaction and user\'s preferance and usage'],
        5000 => ['no' => 'Lønn til ansatte', 'en' => '500 Wages and salaries to employees', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5090 => ['no' => 'Periodiseringskonto lønn', 'en' => '509 Accruals account, wages and salaries', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5180 => ['no' => 'Feriepenger beregnet', 'en' => '518 vacation fund estimated', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5182 => ['no' => 'Arbeidsgiveravgift påløpte feriepenger', 'en' => '519 payroll tax accrued', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        52   => ['no' => 'Fordel i arbeidsforhold ', 'en' => '52 Benefit of employment', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5200 => ['no' => 'Fri bil', 'en' => '520 Company car', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5210 => ['no' => 'Fri telefon', 'en' => '521 Company-paid telephone', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5220 => ['no' => 'Fri avis', 'en' => '522 newspaper/media', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5230 => ['no' => 'Fri losji og bolig', 'en' => '523 Company paid accommodation and housing', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5240 => ['no' => 'Rentefordel', 'en' => '524 Interest advantage', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5280 => ['no' => 'Annen fordel i arbeidsforhold', 'en' => '528 other benefits of employment', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5290 => ['no' => 'Motkonto for gruppe 52', 'en' => '529 Contra account for Group 52', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        53   => ['no' => ' Annen oppgavepliktig godtgjørelse ', 'en' => '53 Other reportable remuneration', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5300 => ['no' => 'Tantieme', 'en' => '53 Other reportable remuneration', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5330 => ['no' => 'Godtgjørelse til styre- og bedriftsforsamling', 'en' => '533 Remuneration to the board and corporate assembly', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        54   => ['no' => 'Arbeidsgiveravgift og pensjonskostnad', 'en' => '54 Employers national insurance contributions and pension costs', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5400 => ['no' => 'Arbeidsgiveravgift', 'en' => '540 Employers national insurance contributions', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5420 => ['no' => 'Innberetningspliktig pensjonskostnad', 'en' => '542 Reportable pension costs', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        55   => ['no' => 'Annen kostnadsgodtgjørelse', 'en' => '55 Other expense allowances', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5500 => ['no' => 'Annen kostnadsgodtgjørelse', 'en' => '550 other expense allowances', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        56   => ['no' => 'Arbeidsgodtgjørelse til eiere o.l. ', 'en' => '56 Labor remuneration to owners etc.', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5600 => ['no' => 'Arbeidsgodtgjørelse til eiere i ANS o l', 'en' => '560 Labor remuneration to partnership owners etc.', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        57   => ['no' => 'Offentlig tilskudd vedr. arbeidskraft ', 'en' => '57 Public work grant', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5700 => ['no' => 'Lærlingtilskudd', 'en' => '570 Apprentice grant', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        58   => ['no' => 'Offentlig refusjon vedr. arbeidskraft ', 'en' => '58 Public refunds related to labor', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5800 => ['no' => 'Refusjon av sykepenger', 'en' => '580 Reimbursements of sickness benefits', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5820 => ['no' => 'Refusjon av arbeidsgiveravgift', 'en' => '582 Reimbursement of national insurance contributions', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        59   => ['no' => 'Annen personalkostnad ', 'en' => '59 Other personnel costs', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5900 => ['no' => 'Gaver til ansatte', 'en' => '590 Gifts to employees', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5910 => ['no' => 'Kantinekostnader', 'en' => '591 Canteen costs', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5920 => ['no' => 'Yrkesskadeforsikring', 'en' => '592 Occupational injury insurance', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        5930 => ['no' => 'Andre forsikringer', 'en' => '593 Other insurance not subject to national insurance contributions', 'nature' => 'Nominal', 'subledger' => 'salaries and wages under direct expenses', 'notes' => ''],
        6    => ['no' => 'ANNEN DRIFTSKOSTNAD, AV- OG NEDSKRIVNING ', 'en' => 'Classes 6 and 7 Other operating expenses, depreciation and write downs.', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        60   => ['no' => 'Av- og nedskrivning ', 'en' => '60 Depreciation and write downs.', 'nature' => 'Nominal', 'subledger' => 'Depreciation', 'notes' => 'Relevant subledgers to be created as per percentage and on different Asset groups and used depending on users need'],
        6000 => ['no' => 'Avskrivning på bygninger og annen fast eiendom', 'en' => '600 Depreciation of buildings and other real property.', 'nature' => 'Nominal', 'subledger' => 'Depreciation', 'notes' => ''],
        6010 => ['no' => 'Avskrivning på transportmidler, mask. og invent.', 'en' => '601 Depreciation of means of transport, machinery, fixtures and fittings.', 'nature' => 'Nominal', 'subledger' => 'Depreciation', 'notes' => ''],
        6020 => ['no' => 'Avskrivning på immatrielle eiendeler', 'en' => '602 Depreciation of intangible fixed assets', 'nature' => 'Nominal', 'subledger' => 'Depreciation', 'notes' => ''],
        6050 => ['no' => 'Nedskrivning av varige driftsmidler', 'en' => '605 Write down of tangible and intangible fixed assets.', 'nature' => 'Nominal', 'subledger' => 'Depreciation', 'notes' => ''],
        61   => ['no' => 'Frakt og transportkostnad vedrørende salg ', 'en' => '61 Freight and transport costs related to sales', 'nature' => 'Nominal', 'subledger' => 'Freight', 'notes' => ''],
        6100 => ['no' => 'Frakt, transportkostnad og forsikring', 'en' => '610 Freight, transport costs and insurance for shipment of goods', 'nature' => 'Nominal', 'subledger' => 'Freight', 'notes' => ''],
        6110 => ['no' => 'Toll og spedisjonskostnad', 'en' => '611 Customs duty and forwarding costs for shipment of goods', 'nature' => 'Nominal', 'subledger' => 'Freight', 'notes' => ''],
        62   => ['no' => 'Energi, brensel og vann vedr. produksjon ', 'en' => '62 Energy, fuel and water related to production', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => 'It is general expense head. User can create a sub ledger as per its need'],
        6200 => ['no' => 'Elektrisitet', 'en' => '620 Electricity', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        6210 => ['no' => 'Gass', 'en' => '621 Gas', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        6220 => ['no' => 'Fyringsolje', 'en' => '622 Heating oil', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        6230 => ['no' => 'Kull, koks', 'en' => '623 Coal or coke', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        6240 => ['no' => 'Ved', 'en' => '624 Firewood', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        6250 => ['no' => 'Bensin, dieselolje', 'en' => '625 Petrol, diesel fuel', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        6260 => ['no' => 'Vann', 'en' => '626 Water', 'nature' => 'Nominal', 'subledger' => 'Energy and fuel', 'notes' => ''],
        63   => ['no' => ' Kostnad lokaler ', 'en' => '63 Costs related to premises', 'nature' => 'Nominal', 'subledger' => 'Premises cost', 'notes' => ''],
        6300 => ['no' => 'Leie lokaler', 'en' => '630 Rental of premises', 'nature' => 'Nominal', 'subledger' => 'Premises cost', 'notes' => ''],
        6320 => ['no' => 'Renovasjon, vann, avløp mv.', 'en' => '632 Waste disposal, water, sewage etc.', 'nature' => 'Nominal', 'subledger' => 'Premises cost', 'notes' => ''],
        6340 => ['no' => 'Lys, varme', 'en' => '634 Lighting, heating', 'nature' => 'Nominal', 'subledger' => 'Premises cost', 'notes' => ''],
        6360 => ['no' => 'Renhold', 'en' => '636 Cleaning', 'nature' => 'Nominal', 'subledger' => 'Premises cost', 'notes' => ''],
        64   => ['no' => 'Leie maskiner, inventar o.l.', 'en' => '64 Rental of machinery, fixtures, fittings etc.', 'nature' => 'Nominal', 'subledger' => 'Rental', 'notes' => ''],
        6400 => ['no' => 'Leie maskiner', 'en' => '640 Rental of machinery', 'nature' => 'Nominal', 'subledger' => 'Rental', 'notes' => ''],
        6410 => ['no' => 'Leie inventar', 'en' => '641 Rental of fixtures and fittings', 'nature' => 'Nominal', 'subledger' => 'Rental', 'notes' => ''],
        6420 => ['no' => 'Leie datasystemer', 'en' => '642 Rental of computer systems', 'nature' => 'Nominal', 'subledger' => 'Rental', 'notes' => ''],
        6430 => ['no' => 'Leie andre kontormaskiner', 'en' => '643 Rental of other office machines', 'nature' => 'Nominal', 'subledger' => 'Rental', 'notes' => ''],
        6440 => ['no' => 'Leie transportmidler', 'en' => '644 Rental of means of transport', 'nature' => 'Nominal', 'subledger' => 'Rental', 'notes' => ''],
        65   => ['no' => 'Verktøy, inventar og driftsmateriale som ikke skal aktiveres ', 'en' => '65 Tools, fixtures, fittings and  operating materials that are not being capitalized.', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6500 => ['no' => 'Motordrevet verktøy', 'en' => '650 Motorized tools', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6510 => ['no' => 'Håndverktøy', 'en' => '651 Hand tools', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6520 => ['no' => 'Hjelpeverktøy', 'en' => '652 Auxiliary tools', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6530 => ['no' => 'Spesialverktøy', 'en' => '653 Special tools', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6540 => ['no' => 'Inventar', 'en' => '654 Fixtures and fittings', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6550 => ['no' => 'Driftsmateriale', 'en' => '655 Operating materials', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6560 => ['no' => 'Rekvisita', 'en' => '656 Supplies', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        6570 => ['no' => 'Arbeidsklær og verneutstyr', 'en' => '657 Work clothing and protective gears', 'nature' => 'Nominal', 'subledger' => 'Repair and other materials', 'notes' => ''],
        66   => ['no' => ' Reparasjon og vedlikehold ', 'en' => '66 Repairs and maintenance', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        6600 => ['no' => 'Reparasjon og vedlikehold bygninger', 'en' => '660 Repair and maintenance of buildings', 'nature' => 'Nominal', 'subledger' => 'Repairs and maintenance', 'notes' => ''],
        6620 => ['no' => 'Reparasjon og vedlikehold utstyr', 'en' => '662 Repair and maintenance of equipment', 'nature' => 'Nominal', 'subledger' => 'Repairs and maintenance', 'notes' => ''],
        67   => ['no' => ' Fremmed tjeneste ', 'en' => '67 External services', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        6700 => ['no' => 'Revisjons- og regnskapshonorarer', 'en' => '670 Auditors remuneration and accountants’ fee', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        6720 => ['no' => 'Honorarer for økonomisk og juridisk bistand', 'en' => '672 Fees for financial aid and legal services', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        68   => ['no' => 'Kontorkostnad, trykksak o.l. ', 'en' => '68 Office costs, printed matter etc.', 'nature' => 'Nominal', 'subledger' => 'Printing & Stationery', 'notes' => ''],
        6800 => ['no' => 'Kontorrekvisita', 'en' => '680 Office supplies', 'nature' => 'Nominal', 'subledger' => 'Printing & Stationery', 'notes' => ''],
        6820 => ['no' => 'Trykksaker', 'en' => '682 Printed matter', 'nature' => 'Nominal', 'subledger' => 'Printing & Stationery', 'notes' => ''],
        6840 => ['no' => 'Aviser og tidsskrifter, bøker o l', 'en' => '684 Newspapers, periodicals, books etc.', 'nature' => 'Nominal', 'subledger' => 'Printing & Stationery', 'notes' => ''],
        6860 => ['no' => 'Møte, kurs, oppdatering o l', 'en' => '686 Meetings, courses, refresher courses etc.', 'nature' => 'Nominal', 'subledger' => 'Printing & Stationery', 'notes' => ''],
        69   => ['no' => 'Telefon, porto o.l. ', 'en' => '69 Telephone, postage etc.', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        6900 => ['no' => 'Telefon', 'en' => '690 Telephone', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        6940 => ['no' => 'Porto', 'en' => '694 Postage', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        7    => ['no' => 'ANNEN DRIFTSKOSTNAD, AV- OG NEDSKRIVNING ', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        70   => ['no' => 'Kostnad transportmidler', 'en' => '70 Costs related to means of transport:', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7000 => ['no' => 'Drivstoff', 'en' => '700 Fuel', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        7020 => ['no' => 'Vedlikehold', 'en' => '702 Maintenance', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        7040 => ['no' => 'Forsikringer', 'en' => '704 Insurance', 'nature' => 'Nominal', 'subledger' => 'as given', 'notes' => ''],
        71   => ['no' => 'Kostnad og godtgj. for reiser, diett, bil o.l. ', 'en' => '71 Costs and remuneration for travel, subsistence, car etc.', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7100 => ['no' => 'Bilgodtgjørelse, oppgavepliktig', 'en' => '710 Car allowance, reportable', 'nature' => 'Nominal', 'subledger' => 'Travel and conveyance', 'notes' => ''],
        7130 => ['no' => 'Reisekostnad, oppgavepliktig', 'en' => '713 Travel expenses, reportable', 'nature' => 'Nominal', 'subledger' => 'Travel and conveyance', 'notes' => ''],
        7140 => ['no' => 'Reisekostnad, ikke oppgavepliktig', 'en' => '714 Travel expenses, non-reportable', 'nature' => 'Nominal', 'subledger' => 'Travel and conveyance', 'notes' => ''],
        7150 => ['no' => 'Diettkostnader, oppgavepliktig', 'en' => '715 Subsistence expenses, reportable', 'nature' => 'Nominal', 'subledger' => 'Travel and conveyance', 'notes' => ''],
        7160 => ['no' => 'Diettkostnader, ikke oppgavepliktig', 'en' => '716 Subsistence expenses, non-reportable', 'nature' => 'Nominal', 'subledger' => 'Travel and conveyance', 'notes' => ''],
        72   => ['no' => 'Provisjonskostnad ', 'en' => '72 Commission charges', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7200 => ['no' => 'Provisjonskostnader, oppgavepliktig', 'en' => '720 Commission charges, reportable', 'nature' => 'Nominal', 'subledger' => 'Commission charges', 'notes' => ''],
        7210 => ['no' => 'Provisjonskostnader, ikke oppgavepliktig', 'en' => '721 Commission charges, non-reportable', 'nature' => 'Nominal', 'subledger' => 'Commission charges', 'notes' => ''],
        73   => ['no' => 'Salgs-, reklame- og representasjonskostn. ', 'en' => '73 Sales, advertising and entertainment expenses', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7300 => ['no' => 'Salgskostnad', 'en' => '730 Selling costs:', 'nature' => 'Nominal', 'subledger' => 'Sales and Advertisement', 'notes' => ''],
        7320 => ['no' => 'Reklamekostnad', 'en' => '732 Advertising costs', 'nature' => 'Nominal', 'subledger' => 'Sales and Advertisement', 'notes' => ''],
        7350 => ['no' => 'Representasjon, fradragsberettiget', 'en' => '735 Entertainment expenses, deductible', 'nature' => 'Nominal', 'subledger' => 'Sales and Advertisement', 'notes' => ''],
        7360 => ['no' => 'Representasjon, ikke fradragsberettiget', 'en' => '736 Entertainment expenses, non-deductible', 'nature' => 'Nominal', 'subledger' => 'Sales and Advertisement', 'notes' => ''],
        74   => ['no' => 'Kontingent og gave ', 'en' => '74 Membership dues and gifts', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7400 => ['no' => 'Kontingenter, fradragsberettiget', 'en' => '740 Membership dues, deductible', 'nature' => 'Nominal', 'subledger' => 'Membership fees', 'notes' => ''],
        7410 => ['no' => 'Kontingenter, ikke fradragsberettiget', 'en' => '741 Membership dues, non-deductible', 'nature' => 'Nominal', 'subledger' => 'Membership fees', 'notes' => ''],
        7420 => ['no' => 'Gaver, fradragsberettiget', 'en' => '742 Gifts, deductible', 'nature' => 'Nominal', 'subledger' => 'Membership fees', 'notes' => ''],
        7430 => ['no' => 'Gaver, ikke fradragsberettiget', 'en' => '743 Gifts non-deductible', 'nature' => 'Nominal', 'subledger' => 'Membership fees', 'notes' => ''],
        75   => ['no' => ' Forsikringspremie, garanti- og servicekostnad ', 'en' => '75 Insurance premiums, guarantee and service costs.', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7500 => ['no' => 'Forsikringspremie', 'en' => '750 Insurance premiums', 'nature' => 'Nominal', 'subledger' => 'Insurance fees', 'notes' => ''],
        7550 => ['no' => 'Garantikostnad', 'en' => '755 Guaranteed costs', 'nature' => 'Nominal', 'subledger' => 'Insurance fees', 'notes' => ''],
        7560 => ['no' => 'Servicekostnad', 'en' => '756 Service costs', 'nature' => 'Nominal', 'subledger' => 'Insurance fees', 'notes' => ''],
        76   => ['no' => ' Lisens- og patentkostnad ', 'en' => '76 License and patent costs', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7600 => ['no' => 'Lisensavgifter og royalties', 'en' => '760 License fees and royalties', 'nature' => 'Nominal', 'subledger' => 'License and patent cost', 'notes' => ''],
        7610 => ['no' => 'Patentkostnad ved egen patent', 'en' => '761 Patent costs for own patents', 'nature' => 'Nominal', 'subledger' => 'License and patent cost', 'notes' => ''],
        7620 => ['no' => 'Kostnader ved varemerker o l', 'en' => '762 Costs related to trademarks etc.', 'nature' => 'Nominal', 'subledger' => 'License and patent cost', 'notes' => ''],
        7630 => ['no' => 'Kontroll-,prøve- og stempelavgifter', 'en' => '763 Inspection, testing and stamp duty fees.', 'nature' => 'Nominal', 'subledger' => 'License and patent cost', 'notes' => ''],
        77   => ['no' => ' Annen kostnad ', 'en' => '77 Other expenses', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7700 => ['no' => 'Styre- og bedriftsforsamlingsmøter', 'en' => '771 Board and corporate assembly meetings', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => 'Can be created as another item of expense depending on users need'],
        7710 => ['no' => 'Generalforsamling', 'en' => '772 General meeting', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7730 => ['no' => 'Kostnader ved egne aksjer', 'en' => '773 Cost of own shares (treasury stock)', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7740 => ['no' => 'Øreavrunding, MVA - oppgjør', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        7745 => ['no' => 'Øreavrunding, avgiftspliktig', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        7746 => ['no' => 'Øreavrunding, avgiftsfritt', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        7750 => ['no' => 'Eiendoms- og festeavgifter', 'en' => '775 Property tax and ground rent', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7770 => ['no' => 'Bank og kortgebyrer', 'en' => '777 Bank charges and card fees', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7780 => ['no' => 'Renter og gebyrer inkasso', 'en' => '778 Interest and collection fees', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7790 => ['no' => 'Andre utgifter', 'en' => '779 Other expenses', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        78   => ['no' => 'Tap o.l. ', 'en' => '78 Losses Etc.', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7800 => ['no' => 'Tap ved avgang driftsmidler', 'en' => '780 Loss on disposal of fixed assets', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7820 => ['no' => 'Innkommet på tidligere nedskrevne fordringer', 'en' => '782 Income on bad debts previously written off', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7830 => ['no' => 'Tap på fordringer', 'en' => '783 Bad debts', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        7860 => ['no' => 'Tap på kontrakter', 'en' => '786 Losses on contracts', 'nature' => 'Nominal', 'subledger' => 'Other miscellaneous cost', 'notes' => ''],
        79   => ['no' => 'Periodiseringskonto ', 'en' => '79 Accruals account', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        7900 => ['no' => 'Beholdningsendring anlegg under utførelse', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        7910 => ['no' => 'Ukurante varer', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        8    => ['no' => 'FINANSINNTEKT OG -KOSTNAD ', 'en' => '80 Financial income', 'nature' => 'Nominal', 'subledger' => '', 'notes' => ''],
        80   => ['no' => 'Finansinntekt ', 'en' => '80 Financial income', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8000 => ['no' => 'Inntekt på investering i datterselskap', 'en' => '800 Income from investments in subsidiaries', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8010 => ['no' => 'Inntekt på investering i annet foretak. s/ konsern', 'en' => '801 Income from investments in other group companies', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8020 => ['no' => 'Inntekt på investering i tilknyttet selskap', 'en' => '802 Income from investments in other group companies', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8030 => ['no' => 'Renteinntekt på foretak i  samme konsern', 'en' => '803 Interest received from group companies', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8040 => ['no' => 'Renteinntekter, skattefrie', 'en' => '804 Interest income, tax exempt.', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8050 => ['no' => 'Annen renteinntekt', 'en' => '805 Other interest income.', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8060 => ['no' => 'Valutagevinst (agio)', 'en' => '806 Foreign exchange gains (agio)', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8070 => ['no' => 'Annen finansinntekt', 'en' => '807 Other financial income', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8080 => ['no' => 'Verdiøkning finansielle omløpsmidler', 'en' => '808 Increase in value of financial instruments', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8090 => ['no' => 'Annen finansinntekt', 'en' => '809 Income from other investments', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        81   => ['no' => ' Finanskostnad ', 'en' => '81 Financial expenses', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8100 => ['no' => 'Verdireduksjon finansielle omløpsmidler', 'en' => '810 Reduction in value of financial instruments valued at fair value', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8110 => ['no' => 'Nedskrivning finansielle omløpsmidler', 'en' => '811 Write-down of other financial current assets', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8120 => ['no' => 'Nedskrivning finansielle anleggsmidler', 'en' => '812 Write-down of long term financial assets', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8130 => ['no' => 'Rentekostnad foretak i samme konsern', 'en' => '813 Interest paid to group companies', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8140 => ['no' => 'Rentekostnad, ikke fradragsberettiget.', 'en' => '814 Interest expenses, non-deductible', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8150 => ['no' => 'Annen rentekostnad', 'en' => '815 Other interest expenses', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8160 => ['no' => 'Valutatap (disagio)', 'en' => '816 Foreign exchange losses (disagio)', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8170 => ['no' => 'Annen finanskostnad', 'en' => '817 Other financial expenses', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        83   => ['no' => ' Skattekostnad på ordinært resultat ', 'en' => '83 Tax on ordinary result', 'nature' => 'Nominal', 'subledger' => 'Duties and taxes as mentioned above', 'notes' => ''],
        8300 => ['no' => 'Betalbar skatt', 'en' => '830 Tax payable', 'nature' => 'Nominal', 'subledger' => 'Duties and taxes as mentioned above', 'notes' => ''],
        8320 => ['no' => 'Utsatt skatt', 'en' => '832 Change in deferred tax/tax assets', 'nature' => 'Nominal', 'subledger' => 'Duties and taxes as mentioned above', 'notes' => ''],
        84   => ['no' => 'Ekstraordinær inntekt (spesifisert etter art) ', 'en' => '84 Extraordinary income (specified by category)', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        8400 => ['no' => 'Ekstraordinær inntekt', 'en' => '84 Extraordinary income (specified by category)', 'nature' => 'Nominal', 'subledger' => 'Other Non operating Income', 'notes' => ''],
        85   => ['no' => 'Ekstraordinær kostnad (spesifisert etter art) ', 'en' => '85 Extraordinary expenses (specified by category)', 'nature' => 'Nominal', 'subledger' => 'As given', 'notes' => ''],
        8500 => ['no' => 'Ekstraordinær kostnad', 'en' => '850 Extraordinary expenses (specified by category', 'nature' => 'Nominal', 'subledger' => 'As given', 'notes' => ''],
        86   => ['no' => 'Skattekostnad på ekstraordinært resultat ', 'en' => '86 Tax on extraordinary result', 'nature' => 'Nominal', 'subledger' => 'Duties and taxes as mentioned above', 'notes' => ''],
        8600 => ['no' => 'Betalbar skatt, ekstraordinært resultat', 'en' => '860 tax payable', 'nature' => 'Nominal', 'subledger' => 'Duties and taxes as mentioned above', 'notes' => ''],
        8620 => ['no' => 'Utsatt skatt, ekstraordinært resultat', 'en' => '862 Change in deferred tax, tax assets', 'nature' => 'Nominal', 'subledger' => 'Duties and taxes as mentioned above', 'notes' => ''],
        88   => ['no' => 'Årsresultat ', 'en' => '88 Net profit/loss for the year', 'nature' => 'Nominal', 'subledger' => 'Part of profit & loss account', 'notes' => ''],
        8800 => ['no' => 'Årsresultat', 'en' => '880 Net profit/loss for the year', 'nature' => 'Nominal', 'subledger' => 'Part of profit & loss account', 'notes' => ''],
        89   => ['no' => 'Overføringer og disponeringer ', 'en' => '89 Transfers and allocations', 'nature' => 'Nominal', 'subledger' => 'Equity transactions', 'notes' => ''],
        8900 => ['no' => 'Overføringsfond vurderingsforskjeller', 'en' => '890 Reserve transfers', 'nature' => 'Nominal', 'subledger' => 'Equity transactions', 'notes' => ''],
        8910 => ['no' => 'Overføringsfond felleseid kapital samme foretak.', 'en' => '891 Transfers, jointly owned cooperative share capital for cooperative society', 'nature' => 'Nominal', 'subledger' => 'Equity transactions', 'notes' => ''],
        8920 => ['no' => 'Avsatt utbytte/renter grunnfondsbevis', 'en' => '892 Allocated dividend/interest on primary capital certificate/ dividend for cooperative society', 'nature' => 'Nominal', 'subledger' => 'Equity transactions', 'notes' => ''],
        8930 => ['no' => 'Konsernbidrag', 'en' => '893 Group contributions', 'nature' => 'Nominal', 'subledger' => 'Equity transactions', 'notes' => ''],
        8940 => ['no' => 'Aksjonærbidrag', 'en' => '', 'nature' => '', 'subledger' => '', 'notes' => ''],
        8950 => ['no' => 'Fondsemisjon', 'en' => '895 Bonus issues', 'nature' => 'Nominal', 'subledger' => 'Equity', 'notes' => ''],
        8960 => ['no' => 'Overføring annen egenkapital', 'en' => '896 transfers to other equity', 'nature' => 'Nominal', 'subledger' => 'Equity', 'notes' => ''],
        8990 => ['no' => 'Udekket tap', 'en' => '899 Uncovered losses', 'nature' => 'Nominal', 'subledger' => 'Equity', 'notes' => ''],
    ],

    'vat'   => [
        35 => ['account_code' => '2710', 'display' => 'Domestic Exempt', 'description' => 'Domestic Exempt'],
        20 => ['account_code' => '2712', 'display' => 'Imported services', 'description' => 'Domestic Exempt'],
        25 => ['account_code' => '2711', 'display' => '25', 'description' => 'High Tax'],
        15 => ['account_code' => '2713', 'display' => '15', 'description' => 'Medium Tax'],
        8  => ['account_code' => '2714', 'display' => '8', 'description' => 'Low Tax']
    ],

    'vat_code'   => [
        35 => '2710',
        20 => '2712',
        25 => '2711',
        15 => '2713',
        8  => '2714',

    ],


];